build:
  gradlew: ../
  file: ../app/build.gradle
  ndk:
    abi_64: ndk {abiFilters 'arm64-v8a', 'x86_64'}
    abi_32: ndk {abiFilters 'armeabi-v7a', 'x86'}
  apk_output_dir: ../app/build/outputs/apk/prod/release
  # The mapping file location. 
  mapping_path: ../app/mapping.txt
dest:
  apk_dir: D:/codes/other/LeafNote-resources/apks
community:
  languages_dir: D:/codes/other/LeafNote-Community/languages/app
jiagu:
  exec_path: D:\360jiagubao_windows_64\jiagu\jiagu.jar
  account: xxxx
  password: xxxx
mail:
  receivers:
    - xxxx
  user: xxxx
  password: xxxx
lanzou:
  username: XXXX
  password: XXXX
  ylogin: XXXX
  phpdisk_info: XXXX
